# Generated by Django 3.0.5 on 2020-04-07 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystockinformation',
            options={'verbose_name_plural': 'Company stock information'},
        ),
        migrations.AddField(
            model_name='companystockinformation',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
